FROM owasp/zap2docker-stable

WORKDIR /app

# Copy backend dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy backend code
COPY . .

# Copy startup script
COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
